on:
  push:

name: Build on ARM64

jobs:
  winarm:
    name: Windows ARM64
    runs-on: self-hosted
    timeout-minutes: 120
    env:
      R_CRAN_WEB: "https://cran.rstudio.com"
      CRAN_RSYNC: 'mirrors.nic.cz::CRAN'
    strategy:
      fail-fast: false
      matrix:
        script: [ 'installer' ]
    steps:

    - name: Prepare git
      run: |
        git config --global core.autocrlf false

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 100

    - name: Build and Check
      run: |
        cd $(cygpath $GITHUB_WORKSPACE)
        /home/jeroen/build-ci.sh
      shell: c:\msys64\usr\bin\bash.exe --login {0}

    - name: Print failed tests
      if: failure() && matrix.script == 'check'
      run: tail -n100 tests/*.fail

    - uses: actions/upload-artifact@v3
      with:
        name: installer
        path: src/gnuwin32/installer/R-devel-win.exe
      if: matrix.script == 'installer'
